name: Auto Deploy

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
        
    - name: Restart server
      env:
        SSH_HOST: ${{ secrets.HOST }}
        SSH_USER: ${{ secrets.USER }}
        SSH_PASS: ${{ secrets.PASSWORD }}
      run: |
        # SSH into the server
        sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST <<EOF
        # Pull the latest code
        git pull
        # Install dependencies
        npm install
        # Restart the server
        npm run dev
        EOF